apiVersion: v1
kind: Service
metadata:
  name: mysql-svc
  namespace: back-end
  labels:
    app: mysql
spec:
  ports:
  - port: 3306
    name: mysql
  clusterIP: None # headless
  selector:
    app: mysql
