apiVersion: v1
kind: Pod
metadata:
  name: pingtest
  namespace: front-end
  labels:
    app: web
spec:
  containers:
  - name: web
    image: hifrodo/msa:v3
    resources:
      limits:
        memory: "128Mi"
        cpu: "500m"
    ports:
      - containerPort: 80
